kerickkkkk/love_in_no_words_back_end

- models/tableCodeModel.ts
- models/tableManagementModel.ts
> feat: 定位 與 座位上限 model

- app.ts
- controller/couponsController.ts
- models/couponModel.ts
- routes/coupons.ts
這個版本先把優惠券做起來，
Ａ＋Ｂ
一加一還沒用
還有沒有做優惠券切換的。
> feat: 初版 只有優惠卷

- app.ts
- bin/www.ts
- package-lock.json
- package.json
- routes/index.ts
初步版本 
1. 可以建立 chef, employee的通道 
2. 可以打完 api 後，再由後端發起 通知到前端 chef, or employee 通道
3. 看是要直接 employee -> chef 或者 employee-> 後端 -> chef
> feat: socket.io 初步版本

- utils/dayjs.ts
> fix: 修正日期超出 day js 回 true

- 傲嬌甜點.postman_collection.json
> feat:補上 S-4-1 ~ 4

- controller/seatsController.ts
> fix : 修正新增修改座位沒有傳入座位人數上限

- app.ts
- controller/seatsController.ts
- controller/usersController.ts
- routes/coupons.ts
- routes/orders.ts
- routes/products.ts
- routes/seats.ts
- 傲嬌甜點.postman_collection.json
1. 修正需求
2. api 路徑修改 admin 與 店長權限 包含 seats, orders, products, coupons
> fix : 登入帳號錯誤會噴五百

- controller/productsController.ts
- routes/orders.ts
- 傲嬌甜點.postman_collection.json
> fix: 查詢類別商品 修正  productsType 與更新 postman 檔案

- controller/membersController.ts
fix S-4-2 search result, add test member 1 to 4
> fix S-4-2 search result, add test member 1 to 4

- controller/ordersController.ts
- controller/productsController.ts
- controller/usersController.ts
- models/orderModel.ts
- routes/orders.ts
- routes/products.ts
- 傲嬌甜點.postman_collection.json
> 修正訂單 與 login 資料格式

- controller/membersController.ts
fix 啟用停用與user list同步(isDisabled: false)
> fix 啟用停用與user list同步(isDisabled: false)

- app.ts
- controller/reportsController.ts
- routes/reports.ts
- 傲嬌甜點.postman_collection.json
> feat: 報表 初步

- controller/reportsController.ts
- package-lock.json
- package.json
- routes/reports.ts
- 傲嬌甜點.postman_collection.json
> feat: O-5-4 報表寄送 初版

- controller/ordersController.ts
- 傲嬌甜點.postman_collection.json
> feat: 調整 訂單商品附註 改為 note

- controller/productsController.ts
- controller/usersController.ts
- utils/dayjs.ts
- 傲嬌甜點.postman_collection.json
fix 大量製造訂單測試API 修改為可以輸入月份隨機生成不同日期時間的訂單
> fix O-1-1 獲取使用者列表API修改為每次只取10筆資料減輕DB負擔

- controller/membersController.ts
> fix S-4-1 phone

- controller/couponsController.ts
- controller/ordersController.ts
- controller/productsController.ts
- controller/reportsController.ts
- controller/seatsController.ts
- routes/coupons.ts
- 傲嬌甜點.postman_collection.json
1. 增加店員搜尋優惠卷
2. 修正訂單文字
3. 修正空值會導致五百
> 增加店員搜尋優惠卷與修正空值報錯

- controller/reportsController.ts
> feat: 美化信件

- controller/ordersController.ts
- routes/index.ts
1. 如題
2. 補修正No default engine was specified and no extension was provided. 沒有指定 view engine 的問題
> fix: 修正訂單計算金額 88 折就是 總價乘以 0.88

- .gitignore
- __test__/controller/ordersController.test.ts
- __test__/sample.test.ts
- controller/ordersController.ts
- jest.config.js
- package-lock.json
- package.json
1. 使用 jest 
2. 驗證單一功能
3. 測試用 npm run test:unit
4. 有使用到的就用資料夾分
> feat: 初步測試包含範例

- controller/linePayController.ts
- controller/ordersController.ts
- middleware/auth.ts
1. 修正訂單計算金額方式，包含優惠卷，直接在產品價格直接打折，以符合 Line pay 結帳格式。
2. Line pay 驗證方式帶 input 。
> feat: line pay form type

- controller/ordersController.ts
S-3-2 加入 滿意度與建議
S-3-3 加入 一張訂單對應一張滿意度與建議 的卡控
> Fixed: S-3-2, S-3-3 新增 Rating 及 ID 不能重複輸入

- 傲嬌甜點.postman_collection.json
> feat: 新增 postman O-6-3

- __test__/apiTest/couponsController.test.ts
- __test__/apiTest/seatsController.test.ts
- connection/service/mongoose.ts
- connection/service/redis.ts
- controller/couponsController.ts
- controller/seatsController.ts
- package-lock.json
- package.json
1. 測試 api 有寫一些測試範例 (優惠卷，座位兩個來寫)。
> feat: api test 初步版本

- controller/linePayController.ts
> feat: 增加 get linpay orderNo 驗證 修正導向

- __test__/apiTest/reportsController.test.ts
- __test__/apiTest/seatsController.test.ts
- connection/service/redis.ts
- controller/ordersController.ts
- controller/productsController.ts
- service/handleAllError.ts
1. 新增訂單測試
2. 修改座位測試名稱
3. 測試隔離： 圖片上傳 redis 
4. 訂單計價改成全整數
5. 訂單 新增 修改 刪除 都回傳當下修改的狀態
> feat: 新增訂單測試 修改座位測試名稱 redis 圖片上傳 先測試隔開 訂單計算改成整數

- controller/linePayController.ts
- routes/linePay.ts
- 傲嬌甜點.postman_collection.json
> feat: S-5-2 改用 axios

- __test__/apiTest/abCouponsController.test.ts
- __test__/apiTest/reportsController.test.ts
- controller/abCouponsController.ts
- controller/seatsController.ts
1. 測試 A+B, 訂單 報表 
2. 店長身份已完成對應開發需測試
3. 對應 controller 增加回傳
> feat:  A + B 報表 訂單測試 修改 controller 回傳

- __test__/apiTest/couponsClerkController.test.ts
- controller/couponsController.ts
- controller/ordersController.ts
- package.json
訂單
1. 先給 原價
2. 修正優惠卷會沒有discount
3. A+B 待修
優惠券
1. 修正店員邏輯
2. 增加對 O-4-1 店員獲取優惠活動列表 測試
測試修改
改成 可以手動輸入
Watch Usage
› Press a to run all tests.
› Press f to run only failed tests.
› Press p to filter by a filename regex pattern.
› Press t to filter by a test name regex pattern.
› Press q to quit watch mode.
› Press Enter to trigger a test run.
可以選 a 全部測試
或者選 p 去測試你要測試的檔案
> 訂單 店員優惠卷測試

- controller/ordersController.ts
- routes/orders.ts
- 傲嬌甜點.postman_collection.json
修正：
1. S-3-1 排序修正
2. 廚師改成廚師權限
3. 更新 傲嬌甜點.postman_collection.json
> Fixed S-3-1, router auth, postman JSON file

- __test__/apiTest/ordersController.test.ts
- controller/linePayController.ts
- 傲嬌甜點.postman_collection.json
1. linepay 寫入付款類型
2. 店員訂單測試 S-2-1 ~ S-2-3 S-3-1~S-3-3
3. 補上廚師 api
> linepay, 測試, api 補上

- .github/workflows/main-deploy.yml
- .github/workflows/main-pr.yml
- __test__/apiTest/abCouponsController.test.ts
- __test__/apiTest/reportsController.test.ts
- connection/service/redis.ts
- package-lock.json
- package.json
- service/firebase.ts
> feat: add ci

- app.ts
- controller/linebotController.ts
- package-lock.json
- package.json
- routes/linebot.ts
1. 初步功能：可以針對店名： 回覆傲嬌甜點，組別：南 1 組，其他則回覆 請輸入關鍵字 店名 或組別。
> feat: 新增 linebot

- __test__/apiTest/ordersController.test.ts
- controller/ordersController.ts
- routes/orders.ts
- 傲嬌甜點.postman_collection.json
> S-3-5 查詢訂單結帳狀態

- .github/workflows/main-deploy.yml
- __test__/apiTest/reservationController.test.ts
> fix : 修正 deploy 卡控流程
